Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.define :lamp do |lamp_config|
  	lamp_config.vm.hostname = 'webserver'
	lamp_config.vm.network "private_network", ip: "192.168.50.11"
  end

  config.vm.provider :virtualbox do |vb_config|
   	vb_config.name = "Vagrant - Ubunutu LAMP"
  end

  config.vm.synced_folder "html", "/var/www/html"
end
